name: Semantic Release Version

on: 
  workflow_dispatch:
  push:
      branches:
        - feature/*
        - hotfix/*
        - bugfix/*

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Semantic Release
        id: prerelease-version
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          npm ci
          npx semantic-release --dry-run --branches ${{ github.ref_name }}
          
          if [[ -f ".VERSION" ]]; then
            VERSION=$(cat .VERSION)
          else
            VERSION=$(jq -r '.version' package.json)
          fi

          echo "PRERELEASE_VERSION=$VERSION" >> "$GITHUB_OUTPUT"
    
      - name: get version
        env:
          PRERELEASE_VERSION: ${{ steps.prerelease-version.outputs.PRERELEASE_VERSION }}
        run: |
          echo "The new version is $PRERELEASE_VERSION"